# Generated by Django 3.1 on 2020-08-07 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fullt_api', '0002_auto_20200807_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='user_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fullt_api.user'),
        ),
    ]
